---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Loading required libraries
```{r echo=TRUE}
library(ggplot2)
```

## Loading and preprocessing the data
```{r echo=TRUE}
# Load the data
unzip(zipfile = "./activity.zip", exdir = "./data");
rawData <- read.csv(file="./data/activity.csv",
                    colClasses = c("numeric", "Date", "numeric"))
```


## What is mean total number of steps taken per day?
```{r echo=TRUE}
# Calculate the total number of steps taken each day
# (ignored the missing value) 
total_steps <- aggregate(rawData$steps, by=list(rawData$date), 
                         FUN=sum, na.rm = TRUE)
colnames(total_steps) <- c("Date", "Total")

g <- ggplot(total_steps, aes(x = Date, y = Total)) 
g <- g + geom_bar(stat="identity")
g <- g + labs(y = "Total number of steps")
g <- g + labs(title = "Total number of steps taken each day during Oct and Nov, 2012")
print(g)
```

```{r echo=TRUE}
# Calculate and report the mean and median total number of steps taken per day
mean_total_steps <- aggregate(rawData$steps, by=list(rawData$date), 
                              FUN=mean, na.rm = TRUE)
colnames(mean_total_steps) <- c("Date", "Mean")

median_total_steps <- aggregate(rawData$steps, by=list(rawData$date), 
                                FUN=median, na.rm = TRUE)
colnames(median_total_steps) <- c("Date", "Median")

processed_total_steps <- merge(mean_total_steps, median_total_steps,
                               by = "Date")
```

## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
